export const FETCH_HEALTHCHECK = 'FETCH_HEALTHCHECK';
export const RECEIVE_HEALTHCHECK = 'RECEIVE_HEALTHCHECK';

export const FETCH_LOGIN = 'FETCH_LOGIN';
export const RECEIVE_LOGIN = 'RECEIVE_LOGIN';
export const LOGOUT = 'LOGOUT';

export const RECEIVE_KIOSKS= 'RECEIVE_KIOSKS';
export const SELECT_KIOSK= 'SELECT_KIOSK';

export const RECEIVE_VOLUME= 'RECEIVE_VOLUME';
export const RECEIVE_CUSTOMER= 'RECEIVE_CUSTOMER';

export const RECEIVE_SALES= 'RECEIVE_SALES';
export const FORCE_SALES_UPDATE= 'FORCE_SALES_UPDATE';
export const RECEIVE_SALES_BY_CHANNEL= 'RECEIVE_SALES_BY_CHANNEL';

export const SET_DATE_RANGE = 'SET_DATE_RANGE';

export const RECEIVE_WATER_OPERATIONS = 'RECEIVE_WATER_OPERATIONS';
