export const FETCH_HEALTHCHECK = 'FETCH_HEALTHCHECK';
export const RECEIVE_HEALTHCHECK = 'RECEIVE_HEALTHCHECK';

export const FETCH_LOGIN = 'FETCH_LOGIN';
export const RECEIVE_LOGIN = 'RECEIVE_LOGIN';
export const LOGOUT = 'LOGOUT';

export const RECEIVE_KIOSKS = 'RECEIVE_KIOSKS';
export const SELECT_KIOSK = 'SELECT_KIOSK';

export const RECEIVE_VOLUME = 'RECEIVE_VOLUME';
export const RECEIVE_CUSTOMER = 'RECEIVE_CUSTOMER';

export const RECEIVE_SALES = 'RECEIVE_SALES';
export const FORCE_SALES_UPDATE = 'FORCE_SALES_UPDATE';
export const RECEIVE_SALES_BY_CHANNEL = 'RECEIVE_SALES_BY_CHANNEL';

export const SET_DATE_RANGE = 'SET_DATE_RANGE';

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const TOGGLE_USER_REQUEST = 'TOGGLE_USER_REQUEST';
export const TOGGLE_USER_SUCCESS = 'TOGGLE_USER_SUCCESS';
export const TOGGLE_USER_FAILURE = 'TOGGLE_USER_FAILURE';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';
