export const FETCH_HEALTHCHECK = 'FETCH_HEALTHCHECK';
export const RECEIVE_HEALTHCHECK = 'RECEIVE_HEALTHCHECK';

export const FETCH_LOGIN = 'FETCH_LOGIN';
export const RECEIVE_LOGIN = 'RECEIVE_LOGIN';
export const SET_LOGIN = 'SET_LOGIN';
