
export default mock_customers = [
	{
		"id" : "027a5568-461d-4141-a2df-9472d0ee6063",
		"version" : 2,
		"address" : "",
		"contact_name" : "Arden's sherluis",
		"customer_type_id" : 126,
		"due_amount" : 26400,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "02fd6fca-b4bf-44a1-8755-2667e76560bb",
		"version" : 3,
		"address" : "",
		"contact_name" : "Fleurius  Flerimond",
		"customer_type_id" : 126,
		"due_amount" : 0,
		"gps_coordinates" : "18.73008,-72.42290",
		"kiosk_id" : 101,
		"name" : "boutique du cartier",
		"phone_number" : "36407295",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "blouson.existentiel.lunaire",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null,
		"sales_channel":"reseller"
	},
	{
		"id" : "051d650d-e3a1-4945-9623-396b0ba0a196",
		"version" : 3,
		"address" : "",
		"contact_name" : "Thomas jean Olrich",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "18.73044,-72.42725",
		"kiosk_id" : 101,
		"name" : "faveur de Dieu",
		"phone_number" : "47928986",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "rasoir.relogement.pousser",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null,
		"sales_channel":"reseller"
	},
	{
		"id" : "053488e1-7af4-4408-8d78-f1ea9658e658",
		"version" : 1,
		"address" : "",
		"contact_name" : "Brunel ",
		"customer_type_id" : 121,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "lechic",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null,
		"sales_channel":"reseller"
	},
	{
		"id" : "0588da3b-0407-4482-a869-cdd5d2d260b8",
		"version" : 1,
		"address" : "Titanyen",
		"contact_name" : "Institution St-Dominique",
		"customer_type_id" : 120,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : 0,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null,
		"sales_channel":"reseller"

	},
	{
		"id" : "065b85d7-568c-47a7-b521-677998483174",
		"version" : 1,
		"address" : "",
		"contact_name" : "Nounca",
		"customer_type_id" : 104,
		"due_amount" : 0,
		"gps_coordinates" : "18.74148,-72.43063",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "dynamique.surmouler.prestigieuse",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null,
		"sales_channel":"walkup"

	},
	{
		"id" : "069ca279-dae8-41bd-83ac-424c0c207742",
		"version" : 2,
		"address" : "",
		"contact_name" : "Stivenson",
		"customer_type_id" : 104,
		"due_amount" : 0,
		"gps_coordinates" : "18.73837,-72.42159",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "satisfaire.couper.réveil",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null,
		"sales_channel":"walkup"
	},
	{
		"id" : "06bb9c9a-9755-496d-8af8-dca08ec1c98a",
		"version" : 1,
		"address" : "",
		"contact_name" : "louisemene",
		"customer_type_id" : 126,
		"due_amount" : 0,
		"gps_coordinates" : "18.748780,-72.400336",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null,
		"sales_channel":"reseller"
	},
	{
		"id" : "08b854d4-9846-49c9-ae3a-130ef8814e75",
		"version" : 2,
		"address" : "",
		"contact_name" : "Pierre viergeline",
		"customer_type_id" : 126,
		"due_amount" : 6600,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null,
		"sales_channel":"reseller"
	},
	{
		"id" : "09ede826-eb40-401f-83fc-b7a7ae9421fc",
		"version" : 3,
		"address" : "",
		"contact_name" : "Congréganiste de cabarèt",
		"customer_type_id" : 120,
		"due_amount" : 0,
		"gps_coordinates" : "18.734652,-72.419636",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : 800,
		"what3words" : "ailier.écumeuse.vitrail",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null,
		"sales_channel":"reseller"
	},
	{
		"id" : "0a7809b5-2b21-4b62-b612-cacb121634af",
		"version" : 2,
		"address" : "",
		"contact_name" : "Ysmail Millien",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "18.72928,-72.41854",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "mince.échapper.soulagement",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "0b22e6ff-1657-454d-ab06-6e6f6f6ad838",
		"version" : 1,
		"address" : "",
		"contact_name" : "bernado",
		"customer_type_id" : 126,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "0bf9d00a-f8db-4561-8ced-1e3c698001eb",
		"version" : 1,
		"address" : "Bercy, entrée central St- Yves borlette",
		"contact_name" : "Charles Veilor",
		"customer_type_id" : 123,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "36184220",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "0d281c05-664f-48bf-a0d8-c2326fa245e3",
		"version" : 1,
		"address" : "Haut Damier",
		"contact_name" : "Madame Hénoc",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "Titi Boutique",
		"phone_number" : "33883146",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "0e594287-be07-4e1c-a335-bf135ed94b85",
		"version" : 2,
		"address" : "",
		"contact_name" : "College Moderne  ",
		"customer_type_id" : 120,
		"due_amount" : 0,
		"gps_coordinates" : "18.735801,-72.417158",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : 190,
		"what3words" : "pluvieux.rhéteur.bordons",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "11e1675d-7dcc-4c9d-a0f9-bec29c90b01b",
		"version" : 1,
		"address" : "",
		"contact_name" : "Yvonise Sinor",
		"customer_type_id" : 119,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "134bfd34-fe5f-40dc-b352-1f5e28625c23",
		"version" : 2,
		"address" : "",
		"contact_name" : "Fleurimomd Raymond",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "18.73014,-72.42298",
		"kiosk_id" : 101,
		"name" : "boutik Kay flerimon",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "poulpe.attrapant.graviter",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "138e1598-0996-4783-aa50-9db923059d27",
		"version" : 4,
		"address" : "",
		"contact_name" : "college Bethesda",
		"customer_type_id" : 120,
		"due_amount" : 0,
		"gps_coordinates" : "18.739751,-72.419185",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : 95,
		"what3words" : "inscrire.sablier.rebondir",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "15123199-cba8-4c7e-a404-86c2e987f5e3",
		"version" : 3,
		"address" : "",
		"contact_name" : "centre de formation classique de Cabaret ",
		"customer_type_id" : 120,
		"due_amount" : 0,
		"gps_coordinates" : "18.734316,-72.417419",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : 200,
		"what3words" : "guidant.oubliant.veinure",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "151ef5a8-ebe9-4f78-93fb-c757cfe36cc6",
		"version" : 1,
		"address" : "",
		"contact_name" : "Woody",
		"customer_type_id" : 119,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "15c1b3d6-0125-4005-9aa0-a146e08155d4",
		"version" : 1,
		"address" : "",
		"contact_name" : "Cameau",
		"customer_type_id" : 103,
		"due_amount" : 0,
		"gps_coordinates" : "18.728779,-72.403866",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "3837-3544",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "16d37365-e038-458a-affa-90a3d356d85a",
		"version" : 1,
		"address" : "",
		"contact_name" : "bigore",
		"customer_type_id" : 126,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "17edd20d-c9df-499b-a359-faf14488d65e",
		"version" : 4,
		"address" : "",
		"contact_name" : "Jezi se wa",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "18.74612,-72.40114",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "36595066",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "espoir.causons.rechasser",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "1994bd76-5449-4a7a-9b2d-a82d5f7a205e",
		"version" : 2,
		"address" : "",
		"contact_name" : "Dupado",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "18.72324 -72.37835",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "1a7ac898-901a-4084-8074-7ef76ea3a21e",
		"version" : 3,
		"address" : "",
		"contact_name" : "Pierre Evens Bouquet",
		"customer_type_id" : 103,
		"due_amount" : 0,
		"gps_coordinates" : "18.73536,-72.41944",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "3251-4545",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "patinette.subisse.déclamer",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "1e7c6c61-0450-4083-bbe7-a1cb15fa0ccc",
		"version" : 1,
		"address" : "",
		"contact_name" : "François Friztnie",
		"customer_type_id" : 119,
		"due_amount" : 0,
		"gps_coordinates" : "18.7319290,-72.4181240",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "1f1af397-32a7-4f28-a085-2690eb33ae50",
		"version" : 1,
		"address" : "teleco",
		"contact_name" : "Orelus Eve ",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "47740205",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "2110b5b9-0ef0-4018-8cd9-fcf10b04e750",
		"version" : 2,
		"address" : "",
		"contact_name" : "Pierre Wilda",
		"customer_type_id" : 104,
		"due_amount" : 0,
		"gps_coordinates" : "18.73855,-72.44314",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "candidat.bricolons.attractif",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "212aeed9-c78c-4758-a5be-60716253f73b",
		"version" : 4,
		"address" : "",
		"contact_name" : "Centre Scolaire Jardin Fleuri",
		"customer_type_id" : 120,
		"due_amount" : 0,
		"gps_coordinates" : "18.742003,-72.42645",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : 60,
		"what3words" : "empaqueter.écrivons.jaunir",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "221ddbb6-fe17-4e55-a897-c2a7326ee1d1",
		"version" : 2,
		"address" : "",
		"contact_name" : "Noe Constant",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "18.73914,-72.40630",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "37764131",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "alizé.généraliste.obliquer",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "22960ee0-dcfa-464e-b600-9b23f2483774",
		"version" : 3,
		"address" : "",
		"contact_name" : "Closnick Bien aimé",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "18.74669,-72.41953",
		"kiosk_id" : 101,
		"name" : "pam",
		"phone_number" : "33630379",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "serment.inventer.associative",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "230ee52c-4a04-4264-bb7f-a1d696ce7c91",
		"version" : 1,
		"address" : "",
		"contact_name" : "Beldor Bazelais",
		"customer_type_id" : 126,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "43387051",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "23390ff8-2152-456b-b38e-a02b5892f281",
		"version" : 1,
		"address" : "",
		"contact_name" : "Johannes Aristille",
		"customer_type_id" : 126,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "25991d46-17c2-410f-ab84-5d248b43a8ca",
		"version" : 1,
		"address" : "",
		"contact_name" : "Regina Boutique",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "3250-5640",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "26948dc4-080d-4604-8e62-074c00874cbd",
		"version" : 3,
		"address" : "",
		"contact_name" : "Pettit Jean Joseph Claudell",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "18.73793,-72.40931",
		"kiosk_id" : 101,
		"name" : "Leon dlo",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "convoyer.prédestiner.tige",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "26d7ff72-ea66-4bde-ab6d-cf8b763e673d",
		"version" : 2,
		"address" : "",
		"contact_name" : "jimmy",
		"customer_type_id" : 104,
		"due_amount" : 0,
		"gps_coordinates" : "18.73957,-72.43452",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "devancier.éditant.dateur",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "26ebce9f-5bdd-4526-b973-a30a28e64bc3",
		"version" : 1,
		"address" : "",
		"contact_name" : "Nelson Pierrot",
		"customer_type_id" : 126,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "282d28f4-f9a2-4b64-afbd-a0869d8e5b94",
		"version" : 1,
		"address" : "",
		"contact_name" : "Mme Milot",
		"customer_type_id" : 126,
		"due_amount" : 0,
		"gps_coordinates" : "18.734902,-72.400616",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "2b23fb56-517e-4f5e-b103-3689ab1aceb3",
		"version" : 1,
		"address" : "",
		"contact_name" : "Ambassadeur de Jesus",
		"customer_type_id" : 119,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "2dd198ea-1a2b-4add-933d-3e6767318048",
		"version" : 2,
		"address" : "",
		"contact_name" : "Mme Sonie",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "18.72128,-72.37402",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "réduisons.faxant.âpre",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "2e327ad8-74f6-4681-aafb-93ad6781d8ff",
		"version" : 2,
		"address" : "",
		"contact_name" : "Evens Pierre-Louis",
		"customer_type_id" : 103,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "Lv.Fils",
		"phone_number" : "33880313",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "2e476060-9e16-4746-a96f-913a4efb36cd",
		"version" : 0,
		"address" : null,
		"contact_name" : "Unregistered",
		"customer_type_id" : 123,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "2ea484bf-e8ba-4e5e-86b7-386a2b7b0935",
		"version" : 2,
		"address" : "",
		"contact_name" : "Marie",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "18.73857,-72.40685",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "alignons.écarquiller.lendemain",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "2ef6fd5e-6660-4bca-b297-c73d549d22e2",
		"version" : 3,
		"address" : "",
		"contact_name" : "Pierre  Nounca",
		"customer_type_id" : 104,
		"due_amount" : 0,
		"gps_coordinates" : "18.74148,-72.43063",
		"kiosk_id" : 101,
		"name" : "Nounca",
		"phone_number" : "32627842",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "vitrons.confection.portons",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "30761fa6-4932-4e59-a5d9-e355186f7eb3",
		"version" : 1,
		"address" : "",
		"contact_name" : "juniel",
		"customer_type_id" : 126,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "32fd60dc-c2b0-4791-993e-cbe8d5727074",
		"version" : 1,
		"address" : "garescher raboto",
		"contact_name" : "Bien aimé ermionne\n",
		"customer_type_id" : 104,
		"due_amount" : 0,
		"gps_coordinates" : "18.753919,-72.447793",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "31012386\n",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "3356ff70-f3f8-4097-a11b-3d58178ec629",
		"version" : 1,
		"address" : "Deschappelles route conseille",
		"contact_name" : "Lorminé Fedlaine",
		"customer_type_id" : 104,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "34526890",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "33fce6be-0a15-4243-99f4-fb66fd93ed51",
		"version" : 2,
		"address" : "",
		"contact_name" : "Pierre Monique",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "18.73009,-72.42039",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "34119585",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "indigestion.exposer.foulard",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "340aa537-9c1b-45d4-b35c-ce6505e7841f",
		"version" : 1,
		"address" : "",
		"contact_name" : "Napoleon Venise",
		"customer_type_id" : 126,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "34a85f5b-4d41-4048-92dd-25c860645fe3",
		"version" : 4,
		"address" : "",
		"contact_name" : "Complexe Laurore",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "18.72032,-72.42680",
		"kiosk_id" : 101,
		"name" : "complexe Laurore",
		"phone_number" : "42895106",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "licence.panda.clouer",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "3562bd07-06c1-44b5-bbe1-401d23aeecdf",
		"version" : 2,
		"address" : "",
		"contact_name" : "Mme Duvergla",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "18.73232,-72.40368",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "sécable.dévorons.limer",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "358548d0-5fb2-4d1b-a01a-846ed9d8aa5e",
		"version" : 3,
		"address" : "",
		"contact_name" : "KTSA",
		"customer_type_id" : 104,
		"due_amount" : 0,
		"gps_coordinates" : "18.73401,-72.41791",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "43833291",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "éliminer.logiciel.arguons",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "3a31860f-ec95-4993-8c0c-d898a54939eb",
		"version" : 1,
		"address" : "",
		"contact_name" : "Hermilus Sorel",
		"customer_type_id" : 104,
		"due_amount" : 0,
		"gps_coordinates" : "18.7377840,-72.4231970",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "3b93bf49-6e66-4ce0-9d68-36891a40ce3e",
		"version" : 1,
		"address" : "Village Compassion",
		"contact_name" : "Zéphirin Guerline",
		"customer_type_id" : 104,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "48252165",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "3bd64e41-11c5-4b22-aad5-2c45bae26d81",
		"version" : 1,
		"address" : "",
		"contact_name" : "Guerline Zéphirin",
		"customer_type_id" : 104,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "48252165",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "3d3e96d9-c047-402c-b072-6aa45a214441",
		"version" : 1,
		"address" : "Haut Damier",
		"contact_name" : "Brice Levelt Sadrac",
		"customer_type_id" : 104,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "La foi en Christ",
		"phone_number" : "34103532",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "3dc904e3-1281-4019-b3fd-393623267d2e",
		"version" : 1,
		"address" : "",
		"contact_name" : "ysmail",
		"customer_type_id" : 126,
		"due_amount" : 0,
		"gps_coordinates" : "18.72928,-72.41854",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "mince.échapper.soulagement",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "3e3d513b-912a-46d3-9008-2f384d9490b3",
		"version" : 2,
		"address" : "",
		"contact_name" : "Noël Evans",
		"customer_type_id" : 126,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "407a5df8-d9c8-42f5-bc05-165808b430cf",
		"version" : 1,
		"address" : "Dibusson\n",
		"contact_name" : "Diana Guillaume",
		"customer_type_id" : 126,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "38943731",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "4368f8dc-12e9-4b4c-a216-8a11396f1c6f",
		"version" : 1,
		"address" : "",
		"contact_name" : "Ruth Wilkianara\n",
		"customer_type_id" : 123,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "31236737 / ",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "443825f9-c1ab-46b5-8d20-15cf03ddf9b6",
		"version" : 3,
		"address" : "",
		"contact_name" : "Elsie Sanon",
		"customer_type_id" : 104,
		"due_amount" : 0,
		"gps_coordinates" : "18.74593,-72.40369",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "43791575",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "macérer.convenance.barreur",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "446718e6-b80e-4cce-a903-45003327a687",
		"version" : 1,
		"address" : "",
		"contact_name" : "Valciné Venat",
		"customer_type_id" : 104,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "40727736",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "448b7a3b-f63b-4b8d-b5e2-0a0bfde22f43",
		"version" : 1,
		"address" : "",
		"contact_name" : "kyky",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "45040505-16b3-4f31-9b50-2daffaa1f12e",
		"version" : 1,
		"address" : "",
		"contact_name" : "fonisd",
		"customer_type_id" : 126,
		"due_amount" : 0,
		"gps_coordinates" : "18.73961,-72.42642",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "étouffante.orage.parier",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "45cdd62e-5095-4a86-be74-4a4cd72b8f41",
		"version" : 2,
		"address" : "",
		"contact_name" : "Rodlande",
		"customer_type_id" : 104,
		"due_amount" : 0,
		"gps_coordinates" : "18.73201,-72.42126",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "ombrons.guêpe.épier",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "4618f56e-ee41-4934-82d1-1f2725e93d8e",
		"version" : 4,
		"address" : "",
		"contact_name" : "Mme Alexandra ",
		"customer_type_id" : 126,
		"due_amount" : 1550,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "46dbf16d-c2bd-417c-a986-d2029ea03f39",
		"version" : 1,
		"address" : "",
		"contact_name" : "Fernande Jean",
		"customer_type_id" : 119,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "48311f98-b543-4077-a187-66cbf2f2363b",
		"version" : 2,
		"address" : "Haut Damier",
		"contact_name" : "Casimir",
		"customer_type_id" : 104,
		"due_amount" : 0,
		"gps_coordinates" : "18.732543,-72.401961",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "48a1099d-299e-4574-976d-3bf57ae7188c",
		"version" : 1,
		"address" : "",
		"contact_name" : "Kès Popilè Kabarè",
		"customer_type_id" : 126,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "28161790",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "49cd0c4b-942d-4fb4-a675-def9ddceb67a",
		"version" : 2,
		"address" : "Fraîche Prince",
		"contact_name" : "Louis Marie Gina",
		"customer_type_id" : 104,
		"due_amount" : 6600,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "4836-4090",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "4e123bbf-fad3-487f-b82c-a1dbcc3a2ce8",
		"version" : 3,
		"address" : "",
		"contact_name" : "Brunick",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "18.73351 -72.44832",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "4ef388b7-bbb7-424b-9627-4bd8f40a4e81",
		"version" : 3,
		"address" : "Haut - Damier",
		"contact_name" : "Rescue of God for the children in Haiti",
		"customer_type_id" : 121,
		"due_amount" : 0,
		"gps_coordinates" : "18.735450,-72.409103",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "37933780",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "510ce652-642e-4dab-9ddc-8ce07e2232ec",
		"version" : 1,
		"address" : "",
		"contact_name" : "Marie Mura",
		"customer_type_id" : 122,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "51550b22-cffe-4a9c-8231-55d8e50f78c0",
		"version" : 1,
		"address" : "",
		"contact_name" : "Cherline Fleuricois",
		"customer_type_id" : 104,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "Biznis lakay",
		"phone_number" : "38573865",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "529add1d-e096-47e0-9d07-a1932eab254e",
		"version" : 2,
		"address" : "",
		"contact_name" : "le chic",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "le chic",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "54d4de0e-3feb-4842-8515-244978c01904",
		"version" : 4,
		"address" : "",
		"contact_name" : "Lycée national de Cabaret ",
		"customer_type_id" : 120,
		"due_amount" : 0,
		"gps_coordinates" : "18.735455,-72.417636",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : 250,
		"what3words" : "mouchant.marchons.secrétaire",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "54eda4f0-9e91-4cf8-b47c-2af98f553d76",
		"version" : 1,
		"address" : "",
		"contact_name" : "Jean Smith Bois",
		"customer_type_id" : 126,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "55c8d3fd-6634-4af9-91d5-8330786decf2",
		"version" : 2,
		"address" : "",
		"contact_name" : "Rose farah",
		"customer_type_id" : 104,
		"due_amount" : 0,
		"gps_coordinates" : "18.759571,-72.444624",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "31588215",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "5662d098-e261-4217-aec5-0c4546a23c84",
		"version" : 2,
		"address" : "",
		"contact_name" : "walkup",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "566feb26-fca1-4827-b363-4bdd09a38dab",
		"version" : 1,
		"address" : "",
		"contact_name" : "Ludens Estilien",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "18.744011,-72.400130",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "3878-9483",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "571d4c8f-bde4-4328-8318-ccb8d6030401",
		"version" : 1,
		"address" : "",
		"contact_name" : "cine palace",
		"customer_type_id" : 126,
		"due_amount" : 0,
		"gps_coordinates" : "18.73619, -72.41917",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "57568e0d-6b8e-40dc-8ec7-d226b67bf0c3",
		"version" : 1,
		"address" : "cité I",
		"contact_name" : "Jérôme Marie Evena",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "18.74612,-72.40114",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "espoir.causons.rechasser",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "59115496-64f8-4379-8068-81fefe72b494",
		"version" : 1,
		"address" : "Foveau",
		"contact_name" : "Jean Ronel Michaud",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "18.720031,-72.425324",
		"kiosk_id" : 101,
		"name" : "Faveur de Dieu",
		"phone_number" : "+50949216979",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "5997fd13-8214-4a42-ad67-5e45d0a39ffd",
		"version" : 2,
		"address" : "Hostin",
		"contact_name" : "Jean Kesny Julien",
		"customer_type_id" : 101,
		"due_amount" : 13200,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "5bbfc8fa-9f0b-46d6-ba3e-a14cb1f8b036",
		"version" : 2,
		"address" : "",
		"contact_name" : "Celestine Clerna",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "18.73622,-72.41801",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "42986610",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "verrière.priver.démener",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "5c58c46d-290f-438b-95f1-c5acc590afbf",
		"version" : 1,
		"address" : "Miami ble",
		"contact_name" : "Rose Marie ",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "39457732",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "5c92756e-3e90-4f61-abec-c9f0a615b006",
		"version" : 1,
		"address" : "",
		"contact_name" : "Family clinic",
		"customer_type_id" : 119,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "5ce6fade-5002-4231-a365-4ee0b52a137a",
		"version" : 2,
		"address" : "",
		"contact_name" : "Jamesline Milfort",
		"customer_type_id" : 102,
		"due_amount" : 0,
		"gps_coordinates" : "18.72572,-72.42374",
		"kiosk_id" : 101,
		"name" : "LaVoix",
		"phone_number" : "38303098",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "pluriel.senteur.attendrir",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "5f6c5a55-41cf-463e-bae9-1bcf48884d9c",
		"version" : 1,
		"address" : "",
		"contact_name" : "Fritz jean Pierre",
		"customer_type_id" : 126,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "6315049c-8517-4af0-8416-6165a41e8d05",
		"version" : 1,
		"address" : "Vignier",
		"contact_name" : "Mme Yvrose Jean Louis",
		"customer_type_id" : 104,
		"due_amount" : 0,
		"gps_coordinates" : "18.772369,-72.469999",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "40805033",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "64e4a935-754b-4f6f-b12e-e32c9444c2af",
		"version" : 3,
		"address" : "",
		"contact_name" : "Geralda Pierre",
		"customer_type_id" : 104,
		"due_amount" : 0,
		"gps_coordinates" : "18.73282 -72.44013",
		"kiosk_id" : 101,
		"name" : "Geralda",
		"phone_number" : "43551645",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "65fa480d-5597-45a8-a21e-f599e40c4891",
		"version" : 1,
		"address" : "Dos Cabaretin ",
		"contact_name" : "Lisa Louijeune",
		"customer_type_id" : 104,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "Kay Monime",
		"phone_number" : "46052267",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "668357e4-2ad5-4279-9af9-d40bb54c6911",
		"version" : 1,
		"address" : "Viau",
		"contact_name" : "Tamoumoune",
		"customer_type_id" : 104,
		"due_amount" : 0,
		"gps_coordinates" : "18.743729,-72.436245",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "6800a283-ba31-464d-a44c-33eeac8d9ac6",
		"version" : 2,
		"address" : "Source Matelas, Derville",
		"contact_name" : "Toussaint Grégory",
		"customer_type_id" : 104,
		"due_amount" : 0,
		"gps_coordinates" : "18.73605,-72.41827",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "36760031",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "pâtissière.fabuleuse.délaver",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "688be860-f2cf-4b5a-8e19-bca803622fe1",
		"version" : 1,
		"address" : "",
		"contact_name" : "Marie Nozilus",
		"customer_type_id" : 126,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "68ef9cfe-632a-4e1f-b20c-f5db604d0de7",
		"version" : 2,
		"address" : "",
		"contact_name" : "Jean Andre",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "18.71747 -72.44011",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "6928765a-144c-4271-a7c1-b4d9cb33298c",
		"version" : 3,
		"address" : "",
		"contact_name" : "Jean Remond",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "18.73412,-72.40177",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "43936104",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "efficace.apurant.alignement",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "697428d1-c14b-4406-979b-528328050041",
		"version" : 1,
		"address" : "Deschappelles (Zo ban)",
		"contact_name" : "Toussaint Magdalena",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "48250522",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "6a8efc5e-f4f4-4576-8020-024f4bda4ec6",
		"version" : 1,
		"address" : "",
		"contact_name" : "stive Deleus",
		"customer_type_id" : 126,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "6af79f83-e68c-478f-bedc-9beb47a9b5cc",
		"version" : 3,
		"address" : "",
		"contact_name" : "Estania Dornelus 2",
		"customer_type_id" : 104,
		"due_amount" : 0,
		"gps_coordinates" : "18.75007,-72.41532",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "frise.désert.matinaux",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "6d0b4ee4-047c-4570-bd70-a538c0e3b2fb",
		"version" : 3,
		"address" : "",
		"contact_name" : "Ecole Nationale de Foveau",
		"customer_type_id" : 120,
		"due_amount" : 0,
		"gps_coordinates" : "18.72347,-72.42535",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : 175,
		"what3words" : "relaver.fâcheux.minime",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "6d9d4ac8-0ff4-406d-919e-31632a0fd13d",
		"version" : 2,
		"address" : "Gariche",
		"contact_name" : "Macula Beauvil",
		"customer_type_id" : 101,
		"due_amount" : 13200,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "6dde97ce-f0b0-4695-ae19-1b155998d5cd",
		"version" : 3,
		"address" : "",
		"contact_name" : "Le sang de Jesus",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "18.72801,-72.41797",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "22263625",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : "serions.olivette.apposer",
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "6e0f0c53-d317-4e39-af36-b6e4033f7083",
		"version" : 2,
		"address" : "",
		"contact_name" : "Nika",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "6fb7738a-99ec-43b6-a5b7-8779af6fd3d9",
		"version" : 2,
		"address" : "",
		"contact_name" : "Rescue or God for the children in Haiti",
		"customer_type_id" : 121,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "37933780 ",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "70b2f1ff-9291-4fbe-aa11-0ff9c95edfdd",
		"version" : 2,
		"address" : "Duclos (zone base)",
		"contact_name" : "Jean Etienne",
		"customer_type_id" : 104,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "+50947898431",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "70f4f48f-0388-4a06-99d2-ea7cb051b70b",
		"version" : 1,
		"address" : "",
		"contact_name" : "Edner Joseph",
		"customer_type_id" : 101,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "71cfcbc3-a2f6-4807-809c-2c6332bbec8b",
		"version" : 1,
		"address" : "",
		"contact_name" : "wilnise",
		"customer_type_id" : 126,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	},
	{
		"id" : "72d419cd-ff6a-4b00-9c6b-ff4a69c3b325",
		"version" : 1,
		"address" : "",
		"contact_name" : "sophonie",
		"customer_type_id" : 126,
		"due_amount" : 0,
		"gps_coordinates" : "",
		"kiosk_id" : 101,
		"name" : "",
		"phone_number" : "",
		"active" : "1",
		"serviceable_customer_base" : null,
		"what3words" : null,
		"notes" : null,
		"multimedia1" : null,
		"multimedia2" : null,
		"multimedia3" : null,
		"gender" : null
	}

]
